---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/ubuntu-ci-tools
    tag: edge

inputs:
  - name: pipeline
  - name: config
  - name: metadata
  - name: stemcell
  - name: logsearch-boshrelease
    optional: true
  - name: logsearch-for-cloudfoundry-boshrelease
    optional: true
  - name: jumpbox-boshrelease
    optional: true
  - name: os-conf-boshrelease
    optional: true
  - name: bosh-vsphere-cpi-boshrelease
    optional: true
  - name: prometheus-boshrelease
    optional: true
  - name: postgres-boshrelease
    optional: true
  - name: cf-routing-boshrelease
    optional: true
  - name: bpm-boshrelease
    optional: true
  - name: concourse-boshrelease
    optional: true
  - name: garden-runc-boshrelease
    optional: true
  - name: backup-and-restore-sdk-boshrelease
    optional: true
  - name: vault-boshrelease
    optional: true
  - name: vault-bbr-boshrelease
    optional: true
  - name: consul-boshrelease
    optional: true
  - name: bosh-boshrelease
    optional: true
  - name: uaa-boshrelease
    optional: true
  - name: toolbelt-boshrelease
    optional: true
  - name: kafka-boshrelease
    optional: true
  - name: kafka-service-broker-boshrelease
    optional: true
  - name: zookeeper-boshrelease
    optional: true
  - name: broker-registrar-boshrelease
    optional: true
  - name: kubo-boshrelease
    optional: true
  - name: cfcr-etcd-boshrelease
    optional: true



outputs:
  - name: config-mod

run:
  path: pipeline/ci/scripts/deploy.sh
